#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep  7 00:28:14 2018

@author: irem
"""
import pygame
import time
import random

pygame.init()

display_width=800
display_height=600

black=(0,0,0)
white=(255,255,255)
red=(200,0,0)
green=(0,200,0)

intro_color=(101,22,219)

bright_red=(255,0,0)
bright_green=(0,255,0)
 
color=(190,13,1)
color2=(235,202,14)

penguin_width=73
penguin_height=82



gameDisplay=pygame.display.set_mode((display_width,display_height))
pygame.display.set_caption('GAME')
clock=pygame.time.Clock()

penguinImg=pygame.image.load('/home/irem/Belgeler/dosya/penguin.jpeg')


def things_dodged(count):
    font=pygame.font.SysFont(None,25)
    text=font.render("Dodged:"+str(count), True,black)
    gameDisplay.blit(text,(360,0))
    

def things(thingx, thingy, thingw,thingh,color):
    pygame.draw.rect(gameDisplay, color, [thingx,thingy,thingw,thingh])
    
#burası kalkacak
def things2(thingx2, thingy2, thingw2,thingh2,color):
    pygame.draw.rect(gameDisplay, color, [thingx2,thingy2,thingw2,thingh2])
    


def penguin(x,y):
    gameDisplay.blit(penguinImg,(x,y))
    
def text_objects(text,font):
    textSurface=font.render(text,True,black)
    return textSurface, textSurface.get_rect()
    
    
def message_display(text):
    largeText=pygame.font.Font('freesansbold.ttf',40)
    TextSurf, TextRect=text_objects(text,largeText)
    TextRect.center=((display_width/2),(display_height/2))
    gameDisplay.blit(TextSurf,TextRect)
    
    pygame.display.update()
    
    time.sleep(2)
    
    game_loop()
    
def crash():
    message_display('Game Over, Skorun: '+str(dodged))
    click=pygame.mouse.get_pressed()
    print(click)
    
def button(msg,x,y,w,h,ic,ac,action=None):
    mouse=pygame.mouse.get_pos()

    click=pygame.mouse.get_pressed()
    
    if x+w>mouse[0] > x and y+h > mouse[1]> y:
        pygame.draw.rect(gameDisplay,ac,(x,y,w,h))
        if click[0]==1 and action != None:
            action()
           
        """     if action=="play":
                game_loop()
            elif action=="quit":
                pygame.quit()
                quit()      """
    else:
        pygame.draw.rect(gameDisplay,ic,(x,y,w,h))
        
    
        
    smallText=pygame.font.Font("freesansbold.ttf",20)
    textSurf,textRect=text_objects(msg,smallText)
    textRect.center=((x+(w/2)),(y+(h/2)))
    gameDisplay.blit(textSurf,textRect)
    
def quitgame():
    pygame.quit()
    quit()
    
    
def game_intro():
    
    intro=True
    
    while intro:
        for event in pygame.event.get():
            if event.type==pygame.QUIT:
                pygame.quit()
                quit()
        
        gameDisplay.fill(intro_color)     
        largeText=pygame.font.Font('freesansbold.ttf',115)   
        TextSurf, TextRect=text_objects("Game",largeText)
        TextRect.center=((display_width/2),(display_height/2))
        gameDisplay.blit(TextSurf,TextRect)
        
        
        button("GO",150,450,100,50,green, bright_green,game_loop)
        button("QUIT",550,450,100,50,red,bright_red,quitgame)
        
        
        #pygame.draw.rect(gameDisplay,red,(550,450,100,50))
        
        pygame.display.update()
        clock.tick(15)
    
    
def game_loop():

    
    x=(display_width*0.45)
    y=(display_height*0.8)   
    
    x_change=0   
    
    thing_startx=random.randrange(0,display_width)
    thing_starty=-600
    thing_speed=8
    thing_width=100
    thing_height=100
    
    """
    #burası klakacak
    thing_startx2=random.randrange(0,display_width)
    thing_starty2=-600
    thing_speed2=6
    thing_width2=100
    thing_height2=100"""
    

    
    global dodged
    dodged=0
    
    gameExit=False
    
    while not gameExit:
        
        for event in pygame.event.get():
            if event.type==pygame.QUIT:
                pygame.quit()
                quit()
                
            if event.type==pygame.KEYDOWN:
                if event.key==pygame.K_LEFT:
                    x_change=-5
                if event.key==pygame.K_RIGHT:
                    x_change=25
            if event.type==pygame.KEYUP:
                if event.key==pygame.K_LEFT or event.key==pygame.K_RIGHT:
                    x_change=0
                    
            
        x+=x_change
        
        gameDisplay.fill(color)
        
        #things(thingx, thingy, thingw,thingh,color)
        things(thing_startx, thing_starty, thing_width,thing_height,color2)
        
        thing_starty+=thing_speed
        
        """
        #burası kalkacak
        things2(thing_startx2, thing_starty2, thing_width2,thing_height2,color2)
        thing_starty2+=thing_speed2
        """
        penguin(x,y)
        things_dodged(dodged)
        
        if x>display_width-penguin_width  or x<0:
            crash()
        
        if thing_starty>display_height:
            thing_starty=0-thing_height
            thing_startx=random.randrange(0,display_width)
            dodged+=1
            #thing_speed+=1   
            
        """      #BURASI KALKACAK
            if thing_starty2>display_height:
            thing_starty2=0-thing_height2
            thing_startx2=random.randrange(0,display_width)
            dodged+=1
            #thing_speed+=1
            #thing_width+=(dodged*1.2)"""
            
            
        if y<thing_starty+thing_height:
            print('y crossover')
            
            if x>thing_startx and x<thing_startx + thing_width  or x+penguin_width > thing_startx and x+penguin_width<thing_startx+thing_width:
                print('x crossover')
                crash()
        """     #BURASI KALKACAK   
        if y<thing_starty2+thing_height2:
            print('y crossover')
            
            if x>thing_startx2 and x<thing_startx2 + thing_width2  or x+penguin_width > thing_startx and x+penguin_width<thing_startx2+thing_width2:
                print('x crossover')
                crash()"""
            
            
        pygame.display.update()
        clock.tick(60)
game_intro()
game_loop()
pygame.quit()
quit()